In [1]:
import numpy as np

In [2]:
#Create a list and convert it to a numpy array
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
#Or just pass in a list directly
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [4]:
#Pass in a list of lists to create a multidimensional array.
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [5]:
#Use the shape method to find the dimensions of the array. (rows, columns)
m.shape

(2, 3)

In [19]:
#arange returns evenly spaced values within a given interval.

n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [37]:
#reshape returns an array with the same data with a new shape.

n = n.reshape(3,5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [29]:
#linspace returns evenly spaced numbers over a specified interval.

o = np.linspace(0, 4, 10) # return 9 evenly spaced values from 0 to 4
o

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [35]:
#resize changes the shape and size of array in-place.

o.resize(5, 2)
o

array([[0.        , 0.44444444],
       [0.88888889, 1.33333333],
       [1.77777778, 2.22222222],
       [2.66666667, 3.11111111],
       [3.55555556, 4.        ]])

In [28]:
#ones returns a new array of given shape and type, filled with ones.

np.ones((3, 2))



array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#zeros returns a new array of given shape and type, filled with zeros.

np.zeros((2, 3))



In [39]:
#eye returns a 2-D array with ones on the diagonal and zeros elsewhere.

np.eye(2)



array([[1., 0.],
       [0., 1.]])

In [38]:
#diag extracts a diagonal or constructs a diagonal array.

np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [40]:
#Create an array using repeating list (or see np.tile)

np.array([1, 2, 3] * 3)



array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [41]:
#Repeat elements of an array using repeat.

np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [44]:
#Combining Arrays
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#Use vstack to stack arrays in sequence vertically (row wise).

np.vstack([p, 2*p])



In [ ]:
#Use hstack to stack arrays in sequence horizontally (column wise).

np.hstack([p, 2*p])

In [ ]:
#Use +, -, *, / and ** to perform element wise addition, subtraction, multiplication, division and power.

print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]



In [ ]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]


In [ ]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

In [ ]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

In [ ]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

In [ ]:
#Let's look at transposing arrays. Transposing permutes the dimensions of the array.

z = np.array([y, y**2])
z



In [ ]:
#The shape of array z is (2,3) before transposing.

z.shape



In [ ]:
#Use .T to get the transpose.

z.T



In [ ]:
#The number of rows has swapped with the number of columns.

z.T.shape

In [ ]:
#Use .dtype to see the data type of the elements in the array.

z.dtype




In [ ]:
#Use .astype to cast to a specific type.

z = z.astype('f')
z.dtype

In [ ]:
#Numpy has many built in math functions that can be performed on arrays.

a = np.array([-4, -2, 1, 3, 5])


In [ ]:
a.sum()


In [ ]:
a.max()


In [ ]:
a.min()


In [ ]:
a.mean()


In [ ]:
a.std()

In [ ]:
#argmax and argmin return the index of the maximum and minimum values in the array.

a.argmax()


In [ ]:
a.argmin()

In [ ]:
#Indexing / Slicing
s = np.arange(13)**2
s

In [ ]:
#Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

s[0], s[4], s[-1]


In [ ]:
#Use : to indicate a range. array[start:stop]

#Leaving start or stop empty will default to the beginning/end of the array.

s[1:5]


In [ ]:
#Use negatives to count from the back.
s[-4:]

In [ ]:
#A second : can be used to indicate step-size. array[start:stop:stepsize]

#Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

s[-5::-2]

In [ ]:
#Let's look at a multidimensional array.

r = np.arange(36)
r.resize((6, 6))
r

In [ ]:
#ue bracket notation to slice: array[row, column]

r[2, 2]



In [ ]:
#and use : to select a range of rows or columns

r[3, 3:6]

In [ ]:
#Here we are selecting all the rows up to (and not including) row 2, 
#and all the columns up to (and not including) the last column.

r[:2, :-1]



In [ ]:
#This is a slice of the last row, and only every other element.

r[-1, ::2]



In [ ]:
#We can also perform conditional indexing. 
#Here we are selecting values from the array that are greater than 30. (Also see np.where)

r[r > 30]



In [ ]:
#Here we are assigning all values in the array that are greater than 30 to the value of 30.

r[r > 30] = 30
r

In [ ]:
#Be careful with copying and modifying arrays in NumPy!

#r2 is a slice of r

r2 = r[:3,:3]
r2



In [ ]:
#Set this slice's values to zero ([:] selects the entire array)

r2[:] = 0
r2



In [ ]:
#r has also been changed!

r

In [ ]:
#To avoid this, use r.copy to create a copy that will not affect the original array
r_copy = r.copy()
r_copy


In [ ]:
#Now when r_copy is modified, r will not be changed.
r_copy[:] = 10
print(r_copy, '\n')
print(r)

In [ ]:
#Let's create a new 4 by 3 array of random numbers 0-9.

test = np.random.randint(0, 10, (4,3))
test

In [ ]:
#Iterate by row:

for row in test:
    print(row)



In [ ]:
#Iterate by index:

for i in range(len(test)):
    print(test[i])



In [ ]:
#Iterate by row and index:

for i, row in enumerate(test):
    print('row', i, 'is', row)

In [ ]:
#Use zip to iterate over multiple iterables.

test2 = test**2
test2


In [ ]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)